// Generated by CoffeeScript 1.10.0
var FlatItem,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

FlatItem = (function(superClass) {
  extend(FlatItem, superClass);

  function FlatItem(name) {
    if (name == null) {
      name = "Flat";
    }
    FlatItem.__super__.constructor.call(this);
    this._name.set(name);
    this._viewable.set(true);
    this.add_attr({
      name: this._name,
      construction: new ConstrainedVal(0, {
        min: 0,
        max: 2
      }),
      fire_detection: new ConstrainedVal(0, {
        min: 0,
        max: 1
      })
    });
    this.add_attr({
      _length: 3.0,
      _width: 2.0,
      _height: 1.0,
      _point: new PointMesher([0, 0, 0], 2, 6)
    });
    this.add_attr({
      _center: this._point.point,
      _mesh: new Mesh({
        not_editable: true
      }),
      _data_visualization: new Choice(0, ["Selection", "Construction", "Fire Detection"])
    });
    this.add_attr({
      length: this._length,
      width: this._width,
      height: this._height,
      center: this._center,
      visualization: this._mesh.visualization,
      _is_selected: 0,
      _is_ok: 0
    });
    this.add_attr({
      color: {
        r: 236,
        g: 236,
        b: 236
      }
    });
    this.normal_display();
  }

  FlatItem.prototype.make_mesh = function() {
    var el, i, j, k, l, num_element, pt_1, pt_2, pt_3, pt_4, x, x_c, y, y_c, z, z_c;
    this._mesh.points.clear();
    this._mesh._elements.clear();
    x = (this._width.get() - 0.2) / 2;
    y = (this._height.get() - 0.2) / 2;
    z = (this._length.get() - 0.2) / 2;
    x_c = this._center.pos[0].get();
    y_c = this._center.pos[1].get();
    z_c = this._center.pos[2].get();
    this._mesh.add_point([x_c - x, y_c - y, z_c - z]);
    this._mesh.add_point([x_c - x, y_c + y, z_c - z]);
    this._mesh.add_point([x_c + x, y_c - y, z_c - z]);
    this._mesh.add_point([x_c + x, y_c + y, z_c - z]);
    this._mesh.add_point([x_c + x, y_c - y, z_c + z]);
    this._mesh.add_point([x_c + x, y_c + y, z_c + z]);
    this._mesh.add_point([x_c - x, y_c - y, z_c + z]);
    this._mesh.add_point([x_c - x, y_c + y, z_c + z]);
    this._mesh.add_point([x_c + x, y_c + y, z_c + z]);
    this._mesh.add_point([x_c + x, y_c + y, z_c - z]);
    this._mesh.add_point([x_c - x, y_c + y, z_c + z]);
    this._mesh.add_point([x_c - x, y_c + y, z_c - z]);
    this._mesh.add_point([x_c - x, y_c - y, z_c + z]);
    this._mesh.add_point([x_c - x, y_c - y, z_c - z]);
    this._mesh.add_point([x_c + x, y_c - y, z_c + z]);
    this._mesh.add_point([x_c + x, y_c - y, z_c - z]);
    el = new Element_TriangleList;
    el.indices.resize([3, 36]);
    num_element = 0;
    for (i = k = 0; k < 6; i = ++k) {
      for (j = l = 0; l < 3; j = ++l) {
        pt_1 = i * 2 + j;
        pt_2 = i * 2 + (j + 1);
        pt_3 = (i + 1) * 2 + j;
        pt_4 = (i + 1) * 2 + (j + 1);
        el.indices.set_val([0, num_element], pt_1);
        el.indices.set_val([1, num_element], pt_3);
        el.indices.set_val([2, num_element], pt_2);
        num_element += 1;
        el.indices.set_val([0, num_element], pt_4);
        el.indices.set_val([1, num_element], pt_2);
        el.indices.set_val([2, num_element], pt_3);
        num_element += 1;
      }
    }
    return this._mesh.add_element(el);
  };

  FlatItem.prototype.draw = function(info) {
    var app_data, sel_items;
    app_data = this.get_app_data();
    sel_items = app_data.selected_tree_items[0];
    if (sel_items != null ? sel_items.has_been_directly_modified() : void 0) {
      if (sel_items[sel_items.length - 1] === this) {
        this._is_selected.set(1);
      } else {
        this._is_selected.set(0);
      }
    }
    if (this._width.has_been_modified() || this._length.has_been_modified() || this._height.has_been_modified() || this._center.has_been_modified()) {
      this.make_mesh();
    }
    if (this._data_visualization.has_been_modified()) {
      this.clear_visu();
      if (this._data_visualization.num.get() === 1) {
        this.construct_building_1();
      } else if (this._data_visualization.num.get() === 2) {
        this.detect_fires();
      }
    }
    if (this._data_visualization.num.get() === 0) {
      this.normal_display();
    }
    if (this._data_visualization.num.get() === 1) {
      this.construct_building_1();
    }
    if (this._data_visualization.num.get() === 2) {
      return this.detect_fires();
    }
  };

  FlatItem.prototype.normal_display = function() {
    if (this._is_selected.get() === 1) {
      this.visualization.display_style.num.set(2);
      this.visualization.element_color.r.val.set(61);
      this.visualization.element_color.g.val.set(134);
      this.visualization.element_color.b.val.set(246);
      return this.visualization.element_color.a.val.set(255);
    } else if (this.fire_detection.get() === 1) {
      this.visualization.display_style.num.set(2);
      this.visualization.element_color.r.val.set(255);
      this.visualization.element_color.g.val.set(0);
      this.visualization.element_color.b.val.set(0);
      return this.visualization.element_color.a.val.set(255);
    } else if (this._is_ok.get() === 1) {
      this.visualization.display_style.num.set(2);
      this.visualization.element_color.r.val.set(0);
      this.visualization.element_color.g.val.set(205);
      this.visualization.element_color.b.val.set(0);
      return this.visualization.element_color.a.val.set(255);
    } else {
      this.visualization.display_style.num.set(2);
      this.visualization.element_color.r.val.set(this.color.r.get());
      this.visualization.element_color.g.val.set(this.color.g.get());
      this.visualization.element_color.b.val.set(this.color.b.get());
      return this.visualization.element_color.a.val.set(255);
    }
  };

  FlatItem.prototype.construct_building_1 = function() {
    if (this.construction.get() === 0) {
      this.visualization.display_style.num.set(1);
      this.visualization.element_color.r.val.set(155);
      this.visualization.element_color.g.val.set(155);
      this.visualization.element_color.b.val.set(155);
      return this.visualization.element_color.a.val.set(255);
    } else if (this.construction.get() === 1) {
      this.visualization.display_style.num.set(2);
      this.visualization.element_color.r.val.set(205);
      this.visualization.element_color.g.val.set(0);
      this.visualization.element_color.b.val.set(0);
      return this.visualization.element_color.a.val.set(255);
    } else if (this.construction.get() === 2) {
      this.visualization.display_style.num.set(2);
      this.visualization.element_color.r.val.set(0);
      this.visualization.element_color.g.val.set(205);
      this.visualization.element_color.b.val.set(0);
      return this.visualization.element_color.a.val.set(255);
    }
  };

  FlatItem.prototype.construct_building_2 = function() {
    if (this.construction.get() === 0) {
      this.visualization.display_style.num.set(2);
      this.visualization.element_color.r.val.set(155);
      this.visualization.element_color.g.val.set(155);
      this.visualization.element_color.b.val.set(155);
      return this.visualization.element_color.a.val.set(255);
    } else if (this.construction.get() === 1) {
      this.visualization.display_style.num.set(2);
      this.visualization.element_color.r.val.set(205);
      this.visualization.element_color.g.val.set(0);
      this.visualization.element_color.b.val.set(0);
      return this.visualization.element_color.a.val.set(255);
    } else if (this.construction.get() === 2) {
      this.visualization.display_style.num.set(2);
      this.visualization.element_color.r.val.set(0);
      this.visualization.element_color.g.val.set(205);
      this.visualization.element_color.b.val.set(0);
      return this.visualization.element_color.a.val.set(255);
    }
  };

  FlatItem.prototype.construct_building_3 = function() {
    if (this.construction.get() === 0) {
      this.visualization.display_style.num.set(3);
      this.visualization.element_color.r.val.set(155);
      this.visualization.element_color.g.val.set(155);
      this.visualization.element_color.b.val.set(155);
      return this.visualization.element_color.a.val.set(30);
    } else if (this.construction.get() === 1) {
      this.visualization.display_style.num.set(3);
      this.visualization.element_color.r.val.set(205);
      this.visualization.element_color.g.val.set(0);
      this.visualization.element_color.b.val.set(0);
      return this.visualization.element_color.a.val.set(130);
    } else if (this.construction.get() === 2) {
      this.visualization.display_style.num.set(3);
      this.visualization.element_color.r.val.set(0);
      this.visualization.element_color.g.val.set(205);
      this.visualization.element_color.b.val.set(0);
      return this.visualization.element_color.a.val.set(255);
    }
  };

  FlatItem.prototype.detect_fires = function() {
    if (this.fire_detection.get() === 0) {
      this.visualization.display_style.num.set(2);
      this.visualization.element_color.r.val.set(155);
      this.visualization.element_color.g.val.set(155);
      this.visualization.element_color.b.val.set(155);
      this.visualization.element_color.a.val.set(255);
    }
    if (this.fire_detection.get() === 1) {
      this.visualization.display_style.num.set(2);
      this.visualization.element_color.r.val.set(205);
      this.visualization.element_color.g.val.set(0);
      this.visualization.element_color.b.val.set(0);
      return this.visualization.element_color.a.val.set(255);
    }
  };

  FlatItem.prototype.clear_visu = function() {
    this.visualization.display_style.num.set(2);
    this.visualization.element_color.r.val.set(155);
    this.visualization.element_color.g.val.set(155);
    this.visualization.element_color.b.val.set(155);
    return this.visualization.element_color.a.val.set(30);
  };

  FlatItem.prototype.cosmetic_attribute = function(name) {
    return FlatItem.__super__.cosmetic_attribute.call(this, name) || (name === "_mesh" || name === "visualization");
  };

  FlatItem.prototype.sub_canvas_items = function() {
    return [this._mesh];
  };

  FlatItem.prototype.is_app_data = function(item) {
    if (item instanceof TreeAppData) {
      return true;
    } else {
      return false;
    }
  };

  FlatItem.prototype.get_app_data = function() {
    var it;
    it = this.get_parents_that_check(this.is_app_data);
    return it[0];
  };

  return FlatItem;

})(TreeItem);
// Generated by CoffeeScript 1.10.0
var eEmployeeItem,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

eEmployeeItem = (function(superClass) {
  extend(eEmployeeItem, superClass);

  function eEmployeeItem(params) {
    if (params == null) {
      params = {};
    }
    eEmployeeItem.__super__.constructor.call(this);
    if (params.name != null) {
      this._name.set(params.name);
    } else {
      this._name.set("Unknown Guy");
    }
    this.add_attr({
      name: this._name,
      id: params.id != null ? params.id : "0",
      phone: params.phone != null ? params.phone : "+336123456780",
      role: new Choice(0, ["directrice", "operateur", "technicien"])
    });
    if (params.role != null) {
      this.role.num.set(params.role);
    }
  }

  return eEmployeeItem;

})(TreeItem);
// Generated by CoffeeScript 1.10.0
var FloorItem,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

FloorItem = (function(superClass) {
  extend(FloorItem, superClass);

  function FloorItem(name, num, params) {
    if (name == null) {
      name = "Floor";
    }
    this.num = num;
    if (params == null) {
      params = {};
    }
    FloorItem.__super__.constructor.call(this);
    this._name.set(name);
    this._viewable.set(false);
    this.make_numa();
  }

  FloorItem.prototype.make_numa = function() {
    var Space_1, Space_2, Space_3, Space_4, Stairs_1, Stairs_2;
    this._children.clear();
    if (this.num <= 5) {
      Space_1 = new FlatItem("Space 1");
      Space_2 = new FlatItem("Space 2");
      Stairs_1 = new FlatItem("Stairs 1");
      this.add_child(Space_1);
      this.add_child(Space_2);
      this.add_child(Stairs_1);
      Space_1._width.set(3);
      Space_1._length.set(3);
      Space_1._height.set(3);
      Space_1._center.pos[0].set(10.5);
      Space_1._center.pos[1].set(3 * this.num + 1.5);
      Space_1._center.pos[2].set(-3.5);
      Space_2._width.set(7);
      Space_2._length.set(7);
      Space_2._height.set(3);
      Space_2._center.pos[0].set(8.5);
      Space_2._center.pos[1].set(3 * this.num + 1.5);
      Space_2._center.pos[2].set(1.5);
      Stairs_1._width.set(4);
      Stairs_1._length.set(3);
      Stairs_1._height.set(3.2);
      Stairs_1._center.pos[0].set(7);
      Stairs_1._center.pos[1].set(3 * this.num + 1.5);
      Stairs_1._center.pos[2].set(-3.5);
      Stairs_1._is_ok.set(1);
    }
    if (this.num <= 4) {
      Space_3 = new FlatItem("Space 3");
      this.add_child(Space_3);
      Space_3._width.set(10);
      Space_3._length.set(10);
      Space_3._height.set(3);
      Space_3._center.pos[0].set(0);
      Space_3._center.pos[1].set(3 * this.num + 1.5);
      Space_3._center.pos[2].set(0);
    }
    if (this.num <= 6) {
      Space_4 = new FlatItem("Space 4");
      Stairs_2 = new FlatItem("Stairs 2");
      this.add_child(Space_4);
      this.add_child(Stairs_2);
      Space_4._width.set(5);
      Space_4._length.set(7);
      Space_4._height.set(3);
      Space_4._center.pos[0].set(-7.5);
      Space_4._center.pos[1].set(3 * this.num + 1.5);
      Space_4._center.pos[2].set(-1.5);
      Stairs_2._width.set(5);
      Stairs_2._length.set(3);
      Stairs_2._height.set(3.2);
      Stairs_2._center.pos[0].set(-7.5);
      Stairs_2._center.pos[1].set(3 * this.num + 1.5);
      Stairs_2._center.pos[2].set(3.5);
      Stairs_2._is_ok.set(1);
    }
    if (this.num === 0) {
      Space_1.color.r.set(35);
      Space_1.color.g.set(31);
      Space_1.color.b.set(32);
      Space_2.color.r.set(35);
      Space_2.color.g.set(31);
      Space_2.color.b.set(32);
      Space_3.color.r.set(35);
      Space_3.color.g.set(31);
      Space_3.color.b.set(32);
      Space_4.color.r.set(35);
      Space_4.color.g.set(31);
      Space_4.color.b.set(32);
    } else if (this.num === 1) {
      Space_1.color.r.set(255);
      Space_1.color.g.set(240);
      Space_1.color.b.set(0);
      Space_2.color.r.set(255);
      Space_2.color.g.set(240);
      Space_2.color.b.set(0);
      Space_3.color.r.set(255);
      Space_3.color.g.set(240);
      Space_3.color.b.set(0);
      Space_4.color.r.set(255);
      Space_4.color.g.set(240);
      Space_4.color.b.set(0);
    } else if (this.num === 2) {
      Space_1.color.r.set(1);
      Space_1.color.g.set(174);
      Space_1.color.b.set(242);
      Space_2.color.r.set(1);
      Space_2.color.g.set(174);
      Space_2.color.b.set(242);
      Space_3.color.r.set(1);
      Space_3.color.g.set(174);
      Space_3.color.b.set(242);
      Space_4.color.r.set(1);
      Space_4.color.g.set(174);
      Space_4.color.b.set(242);
    } else if (this.num === 3) {
      Space_1.color.r.set(239);
      Space_1.color.g.set(31);
      Space_1.color.b.set(143);
      Space_2.color.r.set(239);
      Space_2.color.g.set(31);
      Space_2.color.b.set(143);
      Space_3.color.r.set(239);
      Space_3.color.g.set(31);
      Space_3.color.b.set(143);
      Space_4.color.r.set(239);
      Space_4.color.g.set(31);
      Space_4.color.b.set(143);
    } else if (this.num === 4) {
      Space_1.color.r.set(247);
      Space_1.color.g.set(247);
      Space_1.color.b.set(247);
      Space_2.color.r.set(247);
      Space_2.color.g.set(247);
      Space_2.color.b.set(247);
      Space_3.color.r.set(247);
      Space_3.color.g.set(247);
      Space_3.color.b.set(247);
      Space_4.color.r.set(247);
      Space_4.color.g.set(247);
      Space_4.color.b.set(247);
    } else if (this.num === 5) {
      Space_1.color.r.set(188);
      Space_1.color.g.set(189);
      Space_1.color.b.set(193);
      Space_2.color.r.set(188);
      Space_2.color.g.set(189);
      Space_2.color.b.set(193);
      Space_4.color.r.set(188);
      Space_4.color.g.set(189);
      Space_4.color.b.set(193);
    }
    if (this.num === 6) {
      Space_4.color.r.set(35);
      Space_4.color.g.set(31);
      return Space_4.color.b.set(32);
    }
  };

  return FloorItem;

})(FlatItem);
// Generated by CoffeeScript 1.10.0
var eTeamItem,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

eTeamItem = (function(superClass) {
  extend(eTeamItem, superClass);

  function eTeamItem(name) {
    if (name == null) {
      name = "Team";
    }
    eTeamItem.__super__.constructor.call(this);
    this._name.set(name);
    this.add_attr({
      send_alert: false
    });
  }

  eTeamItem.prototype.display_suppl_context_actions = function(context_action) {
    return context_action.push(new TreeAppModule_AddEmployee);
  };

  eTeamItem.prototype.accept_child = function(ch) {
    return ch instanceof eEmployeeItem;
  };

  return eTeamItem;

})(TreeItem);
// Generated by CoffeeScript 1.10.0
var GroundItem,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

GroundItem = (function(superClass) {
  extend(GroundItem, superClass);

  function GroundItem(name) {
    if (name == null) {
      name = "Ground";
    }
    GroundItem.__super__.constructor.call(this);
    this._name.set(name);
    this._viewable.set(true);
    this.add_attr({
      _width: 40,
      _height: 0.5,
      _point: new PointMesher([0, 0, 0], 2, 6)
    });
    this.add_attr({
      _center: this._point.point
    });
    this.add_attr({
      width: this._width,
      height: this._height,
      center: this._center,
      _mesh: new Mesh({
        not_editable: true
      })
    });
    this.add_attr({
      visualization: this._mesh.visualization
    });
    this.make_mesh();
    this._center.pos[0].set(0);
    this._center.pos[1].set(-this._height / 2);
    this._center.pos[2].set(0);
    this.visualization.display_style.num.set(2);
  }

  GroundItem.prototype.make_mesh = function() {
    var el, i, j, k, l, num_element, pt_1, pt_2, pt_3, pt_4, x, x_c, y, y_c, z, z_c;
    this._mesh.points.clear();
    this._mesh._elements.clear();
    x = this._width.get() / 2;
    y = this._height.get() / 2;
    z = this._width.get() / 2;
    x_c = this._center.pos[0].get();
    y_c = this._center.pos[1].get();
    z_c = this._center.pos[2].get();
    this._mesh.add_point([x_c - x, y_c - y, z_c - z]);
    this._mesh.add_point([x_c - x, y_c + y, z_c - z]);
    this._mesh.add_point([x_c + x, y_c - y, z_c - z]);
    this._mesh.add_point([x_c + x, y_c + y, z_c - z]);
    this._mesh.add_point([x_c + x, y_c - y, z_c + z]);
    this._mesh.add_point([x_c + x, y_c + y, z_c + z]);
    this._mesh.add_point([x_c - x, y_c - y, z_c + z]);
    this._mesh.add_point([x_c - x, y_c + y, z_c + z]);
    this._mesh.add_point([x_c + x, y_c + y, z_c + z]);
    this._mesh.add_point([x_c + x, y_c + y, z_c - z]);
    this._mesh.add_point([x_c - x, y_c + y, z_c + z]);
    this._mesh.add_point([x_c - x, y_c + y, z_c - z]);
    this._mesh.add_point([x_c - x, y_c - y, z_c + z]);
    this._mesh.add_point([x_c - x, y_c - y, z_c - z]);
    this._mesh.add_point([x_c + x, y_c - y, z_c + z]);
    this._mesh.add_point([x_c + x, y_c - y, z_c - z]);
    el = new Element_TriangleList;
    el.indices.resize([3, 36]);
    num_element = 0;
    for (i = k = 0; k < 6; i = ++k) {
      for (j = l = 0; l < 3; j = ++l) {
        pt_1 = i * 2 + j;
        pt_2 = i * 2 + (j + 1);
        pt_3 = (i + 1) * 2 + j;
        pt_4 = (i + 1) * 2 + (j + 1);
        el.indices.set_val([0, num_element], pt_1);
        el.indices.set_val([1, num_element], pt_3);
        el.indices.set_val([2, num_element], pt_2);
        num_element += 1;
        el.indices.set_val([0, num_element], pt_4);
        el.indices.set_val([1, num_element], pt_2);
        el.indices.set_val([2, num_element], pt_3);
        num_element += 1;
      }
    }
    return this._mesh.add_element(el);
  };

  GroundItem.prototype.cosmetic_attribute = function(name) {
    return GroundItem.__super__.cosmetic_attribute.call(this, name) || (name === "_mesh" || name === "visualization");
  };

  GroundItem.prototype.accept_child = function(ch) {};

  GroundItem.prototype.sub_canvas_items = function() {
    return [this._mesh];
  };

  return GroundItem;

})(TreeItem);
// Generated by CoffeeScript 1.10.0
var NumaItem,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

NumaItem = (function(superClass) {
  extend(NumaItem, superClass);

  function NumaItem(name) {
    if (name == null) {
      name = "Numa";
    }
    NumaItem.__super__.constructor.call(this);
    this._name.set(name);
    this._viewable.set(false);
    this.add_attr({
      name: this._name,
      data_visualization: new Choice(0, ["Selection", "Construction", "Fire Detection"])
    });
    this.bind((function(_this) {
      return function() {
        var flat, floor, i, len, ref, results;
        if (_this.data_visualization.has_been_modified() || _this._children.has_been_modified()) {
          ref = _this._children;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            floor = ref[i];
            floor._data_visualization.num.set(_this.data_visualization.num.get());
            results.push((function() {
              var j, len1, ref1, results1;
              ref1 = floor._children;
              results1 = [];
              for (j = 0, len1 = ref1.length; j < len1; j++) {
                flat = ref1[j];
                results1.push(flat._data_visualization.num.set(this.data_visualization.num.get()));
              }
              return results1;
            }).call(_this));
          }
          return results;
        }
      };
    })(this));
  }

  NumaItem.prototype.display_suppl_context_actions = function(context_action) {
    return context_action.push(new TreeAppModule_Numa);
  };

  NumaItem.prototype.accept_child = function(ch) {
    return ch instanceof FloorItem;
  };

  return NumaItem;

})(TreeItem);
